# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.10'
  displayName: 'Install terraform'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'development'
    backendAzureRmResourceGroupName: 'az1'
    backendAzureRmStorageAccountName: 'azstorage1219'
    backendAzureRmContainerName: 'tf-state'
    backendAzureRmKey: 'sample.tfstate'
  displayName: 'Terraform init'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'development'
  displayName: 'Terraform apply'